---
stages:
  - name: Clean Image
    steps: 
      - command: docker system prune
        command: docker volume prune
        command: docker ps
  - name: Download the Project
    steps:
      - command: mkdir -p unfetter-discover
        command: cd unfetter-discover
        command: git clone https://github.com/unfetter-discover/unfetter.git
        command: git clone https://github.com/unfetter-discover/unfetter-ui.git
        command: git clone https://github.com/unfetter-discover/unfetter-store.git
        command: git clone https://github.com/unfetter-discover/stix2pattern.git

  - name: Ansible Deploy Test
    steps: 
      - command: cd unfetter/ansible && ansible-playbook deploy-dev.yml

  - name: Test Image
    steps: 
      - command: docker images
        command: docker container ls

  - name: Verify Image Creation
      when: docker inspect unfetter-discover-api:0.3.10.beta.1 | grep -i created != true

  - name: Verify Container Running
      when: docker inspect 9c475e692abf  | grep -i running != true
  
