config:
  project_name: unfetter_jenkins
services:
  jenkins:
    image: jenkins
    container_name: jenkins
steps:
  delete:
    - ../jenkins/dockerdeletescript.sh
  download:
    - ../jenkins/downloadproject.sh
  validation:
    - ../jenkins/validationtest.sh
  master_test:
    - ../jenkins/ctfingesttestmaster.sh
    - ../jenkins/discoverapitestmaster.sh
    - ../jenkins/discoverprocessormaster.sh
    - ../jenkins/uitestmaster.sh
  develop_test:
    - ../jenkins/ctfingesttestdevelop.sh
    - ../jenkins/discoverapitestmaster.sh
    - ../jenkins/discoverprocessortestdevelop.sh
    - ../jenkins/uitestdevelop.sh
